[profile.default]
solc_version = "0.8.22"
src = "contracts"
out = "out"
libs = ["node_modules", "lib"]
ffi = true
optimizer = true
optimizer_runs = 200
evm_version = 'shanghai'

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[etherscan]
3605 = { key = "none", url = "https://explorer-cloud-broken-leg-7uu20euqoj.t.conduit.xyz/api" }
421614 = { key = "${ARBISCAN_API_KEY}", url = "https://api-sepolia.arbiscan.io/api?" }
11155420 = { key = "${OPTIMISM_API_KEY}", url = "https://optimism-sepolia.blockscout.com/api?" }
